version: '3.8'

services:
  bot:
    build: .
    container_name: exam_tracker_bot
    restart: always
    volumes:
      - ./bot_data:/app/data
    env_file: .env

  dashboard:
    build: .
    container_name: exam_tracker_dashboard
    command: gunicorn --bind 0.0.0.0:5000 dashboard:app
    restart: always
    ports:
      - "5000:5000"
    volumes:
      - ./bot_data:/app/data
    env_file: .env
